/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class packetmaker_RawPacketSender */

#ifndef _Included_packetmaker_RawPacketSender
#define _Included_packetmaker_RawPacketSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     packetmaker_RawPacketSender
 * Method:    sendPacket
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_packetmaker_RawPacketSender_sendPacket
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
