/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class packetconstructor_RawPacketSender */

#ifndef _Included_packetconstructor_RawPacketSender
#define _Included_packetconstuctor_RawPacketSender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     packetconstructor_RawPacketSender
 * Method:    sendPacket
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_packetconstructor_RawPacketSender_sendPacket
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
